# Generated by Django 3.1.3 on 2021-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210823_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='Question',
            field=models.ManyToManyField(to='onlinecourse.Question'),
        ),
    ]
