# Generated by Django 3.2.6 on 2021-08-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20210824_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
    ]
