# Generated by Django 3.2.6 on 2021-08-25 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20210824_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='question content', max_length=200),
        ),
    ]
